name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (auto detects from package.json if not specified)'
        required: false
        type: choice
        options:
          - ''  # Auto-detect
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for release-it
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Set up GPG
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: ${{ secrets.GPG_FINGERPRINT }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      
      - name: Configure git
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Configure npm
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      
      - name: Release
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            npx release-it --only-version --ci ${{ github.event.inputs.version }}
          else
            npx release-it --only-version --ci
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Cleanup
        if: always()
        run: |
          npm config delete //registry.npmjs.org/:_authToken
          gpg --batch --yes --delete-secret-keys ${{ secrets.GPG_FINGERPRINT }} || true
          gpg --batch --yes --delete-keys ${{ secrets.GPG_FINGERPRINT }} || true